apiVersion: v1
kind: Pod
metadata:
  name: agentpod
  labels:
    some-label: pod
spec:
  containers:
    -name : kubectl
     image: bitnami/kubectl:1.18
     command:
       - cat
     tty: true
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
