# Pod Template that is run by the Jenkins agent.
# It has 2 containers,
# - one used on the build process (docker)
# - and one used on the deployment process (kubectl)
apiVersion: v1
kind: Pod
metadata:
  name: agentpod
  labels:
    some-label: pod
spec:
  containers:
    - name : kubectl
      image: dtzar/helm-kubectl:latest
      command:
        - cat
      tty: true
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
